app:
  port: ${PORT:0}
spring:
  application:
    name: resenhas-micro
  datasource:
    url: jdbc:h2:mem:resenhas-micro
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: ${app.port}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
