spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: livros
          uri: lb://ACERVO-MICRO
          filters:
            - StripPrefix=1
          predicates:
            - Path=/livros/**
        - id: autores
          uri: lb://AUTORES-MICRO
          filters:
            - StripPrefix=1
          predicates:
            - Path=/autores/**
        - id: resenhas
          uri: lb://RESENHAS-MICRO
          filters:
            - StripPrefix=1
          predicates:
            - Path=/resenhas/**
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
